---
- name: Overiew of ansible filter and methods
  hosts: localhost
  gather_facts: false

  vars:
    a : "Hello, I am Md JAhid HasaN"
    b : 10
    c : "20"

  tasks:
    - name: Operations on variables
      debug:
        msg:
        - "Value of a is : {{ a }}"
        - "Value of b + c is : {{ b + c|int }}"
        - "Small case value of a : {{ a|lower }}"
        - "Capital case value of a : {{ a|upper }}"
        - "Title case value of a : {{ a|title }}"
        - "Small case value of a : {{ a.lower() }}"
        - "Capital case value of a : {{ a.upper() }}"
        - "Split of string a : {{ a.split() }}"
        - "Split of string a : {{ a.lower().split() }}"
        - "Split of string a : {{ a.upper().split() }}"

