---
- name: Introduction Ansible Playbook
  hosts: all
  remote_user: root
  become: yes

  vars:
    test: Hello, this is a demo value
    my_name: Md Jahid Hasan
    my_age: 29
    my_height: 5.6
    is_male: true

  tasks:
    - name: Reading ansible playbook variable
      debug:
        var: test

    - name: Reading ansible playbook variables
      debug:
        msg:
        - My name is {{ my_name }}
        - I am {{ my_age }} years old.
        - And I am {{ my_height }} long, my gender is male - {{ is_male }}
