---
- name: Overview of ansible include tasks
  hosts: localhost
  remote_user: root
  become: yes
  gather_facts: false

  tasks:
    - name: Play 1 - Task 1
      debug:
        msg: "Play 1 - Task 1"
    - include_tasks: import_include_task.yml

