---
- name: Overview of local action in ansible
  hosts: all
  remote_user: root
  become: yes

  tasks:
    - name: This will create a local file /tmp/local_file.ini
      local_action: command touch /tmp/"{{ ansible_hostname }}"_local_file.ini

    - name: Here we copy the local file to remote
      copy:
        src: /tmp/{{ ansible_hostname }}_local_file.ini
        dest: /var/tmp

