---
- name: Overiew of ansible logical operators
  hosts: localhost
  gather_facts: false

  vars:
    a : "Hello, I am Md JAhid HasaN"
    b : 10
    c : "20"
    d : [ 1, 5, 9, 10, 15, 109 ]
    x : true
    y : false
    z : false
    m : true

  tasks:
    - name: Operations on variables
      debug:
        msg:
        - "x and y : {{ x and y }}"
        - "x and m : {{ x and m }}"
        - "x or m : {{ x or m }}"
        - "y or z : {{ y or z }}"
        - "x and y or m : {{ x and y or m }}"
