---
- name: This is overview of ansible debug module
  hosts: all
  remote_user: root
  become: yes

  tasks:
    - name: Task for debug module messaging
      debug:
        msg: Hi, this is custom message for debug module

    - name:
      debug:
        msg:
        - "Hi, this is a multiline message"
        - "This is line number 2"

    - name: Print variable in message
      debug:
        msg:
        - "Host IP is - {{ inventory_hostname }}"
        - Host IP is {{ inventory_hostname }}
        - System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}

    - name: Debug module var parameter
      debug:
        var: inventory_hostname

    - name: Verbosity in debug module
      debug:
        msg: "Hi, this is deep logging at debug level 2"
        verbosity: 2
